env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  # see: https://eslint.org/docs/rules/
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  prefer-const: error
  no-var: error
  curly: error
  spaced-comment: error
  eqeqeq: error
  complexity: error
  camelcase: error
  no-extra-boolean-cast: off
